DROP TABLE IF EXISTS scores;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS credentials;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    uuid UUID NOT NULL,
    username TEXT UNIQUE NOT NULL,
    about TEXT,
    join_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY(uuid)
);

CREATE TABLE IF NOT EXISTS credentials (
    id INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    owner_uuid UUID NOT NULL REFERENCES users(uuid) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    is_email_confirmed BOOLEAN NOT NULL DEFAULT false,
    pwd_hash TEXT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS posts (
    id INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    owner_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
    date_updated TIMESTAMPTZ,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS scores (
    id INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    owner_id INT UNIQUE NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    score INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
