CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    username TEXT UNIQUE NOT NULL,
    about TEXT,
    join_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS credentials (
    id INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    owner_id INT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    is_email_confirmed BOOLEAN NOT NULL DEFAULT false,
    pwd_hash TEXT NOT NULL,
    PRIMARY KEY(id)
);

